# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release

on:
  push:

#on:
#  push:
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  gcloud_release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: cmake build
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            ./build.sh --config RelWithDebInfo --build_shared_lib --parallel --enable_pybind --skip_tests --build_wheel --cmake_extra_defines
          elif [ "$RUNNER_OS" == "Windows" ]; then
            .\build.bat --config RelWithDebInfo --build_shared_lib --parallel --enable_pybind --skip_tests --build_wheel --cmake_extra_defines
          elif [ "$RUNNER_OS" == "macOS" ]; then
            ./build.sh --config RelWithDebInfo --build_shared_lib --parallel --enable_pybind --skip_tests --build_wheel --cmake_extra_defines CMAKE_OSX_ARCHITECTURES=x86_64
          else
               echo "$RUNNER_OS not supported"
               exit 1
          fi
        working-directory: ${{ github.workspace }}
#      - name: Download build artifacts
#        uses: actions/download-artifact@v3
#        with:
#          name: build-${{ runner.os }}
#          path: bin/
#
#      - name: 'upload-folder'
#        uses: 'google-github-actions/upload-cloud-storage@v0'
#        with:
#          path: bin
#          glob: '*cpuinstructions*.{dylib,so,dll}'
#          destination: pieces-libraries/cpuinstructions/${{ github.ref_name }}
#          parent: false